apiVersion: v1
kind: ReplicaSet
metadata:
  name: nginx-rs-nodeport-k8-service
spec:
  type: NodePort
  ports:
  - name: k8-service
    nodePort: 81 # Listening port on External IPs
    port: 8080 # Listening port on Internal IPs
    protocol: TCP
    targetPort: 8080 # Pod’s listening port
  selector:
    app: nginx-rs-pod